title: Exploring Personal Patterns from Garmin Fitness Data
description: This is my course project for Introduction to Data Science (CS 210) course in Sabancı University, Turkey
theme: jekyll-theme-minimal



